"""add audit fields

Revision ID: 0006
Revises: 0005
Create Date: 2026-01-02 17:07:41.001773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column("project", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("project", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("project", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column("project", sa.Column("updated_by", sa.UUID(), nullable=True))

    # Set default values for existing rows
    op.execute(
        "UPDATE project SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )
    op.execute(
        "UPDATE project SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL"
    )

    # Now alter created_at to be NOT NULL
    op.alter_column("project", "created_at", nullable=False)

    # Add foreign key constraints
    op.create_foreign_key(None, "project", "user", ["created_by"], ["pk"])
    op.create_foreign_key(None, "project", "user", ["updated_by"], ["pk"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "updated_by")
    op.drop_column("project", "created_by")
    op.drop_column("project", "updated_at")
    op.drop_column("project", "created_at")
    # ### end Alembic commands ###
