"""create user, workspace and workspace_member tables with uuid pk

Revision ID: 722f004a966a
Revises: 2883bccc7222
Create Date: 2026-01-01 21:37:06.522488

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "722f004a966a"
down_revision: Union[str, Sequence[str], None] = "2883bccc7222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("pk", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "workspace",
        sa.Column("pk", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_workspace_name"), "workspace", ["name"], unique=True)
    op.create_table(
        "workspace_member",
        sa.Column("pk", sa.UUID(), nullable=False),
        sa.Column("user", sa.UUID(), nullable=False),
        sa.Column("workspace", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["user.pk"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace"], ["workspace.pk"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_member")
    op.drop_index(op.f("ix_workspace_name"), table_name="workspace")
    op.drop_table("workspace")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
