"""create project table

Revision ID: 865371a245d9  # pragma: allowlist secret
Revises: 722f004a966a
Create Date: 2026-01-02 11:45:25.464304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "865371a245d9"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "722f004a966a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("pk", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("workspace", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["workspace"], ["workspace.pk"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project")
    # ### end Alembic commands ###
